name: Bluebird FX
favicon: null
layout_spectrum: 0.5
typography_spectrum: 0.41545
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#615e5e'
    - '#3e3d3c'
    - '#7d859f'
    - '#afb1be'
  brandStrength: 0
  lightness: 0
  saturation: 1
  rhythmicContrast: 0
purpose: []
