name: Bluebird FX
favicon: null
layout_spectrum: 1
typography_spectrum: 0.41545
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0a0a0a'
    - '#79dbf5'
    - '#3a7564'
    - '#d0804f'
    - '#e9be6c'
  brandStrength: 0
  lightness: 1
  saturation: 1
  rhythmicContrast: 1
purpose: []
